name: kasie_transie_demoapp
description: DemoApp Version 3.0

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  kasie_transie_library:
    path: ../kasie_transie_library
  cupertino_icons: ^1.0.6
  realm_dart: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3


flutter:

  uses-material-design: true

  assets:
    - assets/intro/
    - assets/mapicons/
    - assets/l10n/
    - assets/
    - assets/projects/
    - assets/payment/
    - assets/markers/
    - assets/numbers/
    - .env
